export const REGISTER_AUTHUSER_REQUEST = "REGISTER_AUTHUSER_REQUEST";
export const REGISTER_AUTHUSER_SUCCESS = "REGISTER_AUTHUSER_SUCCESS";
export const REGISTER_AUTHUSER_FAILURE = "REGISTER_AUTHUSER_FAILURE";

export const LOGIN_AUTHUSER_REQUEST = "LOGIN_AUTHUSER_REQUEST";
export const LOGIN_AUTHUSER_SUCCESS = "LOGIN_AUTHUSER_SUCCESS";
export const LOGIN_AUTHUSER_FAILURE = "LOGIN_AUTHUSER_FAILURE";