export const CREATE_FILE_REQUEST = "CREATE_FAIL_REQUEST"
export const CREATE_FILE_SUCCESS = "CREATE_FAIL_SUCCESS"
export const CREATE_FILE_FAILURE = "CREATE_FILE_FAILURE"

export const GET_FILE_REQUEST = "GET_FAIL_REQUEST"
export const GET_FILE_SUCCESS = "GET_FAIL_SUCCESS"
export const GET_FILE_FAILURE = "GET_FILE_FAILURE"

export const GET_FILE_BYID_REQUEST = "GET_FAIL_BYID_REQUEST"
export const GET_FILE_BYID_SUCCESS = "GET_FAIL_BYID_SUCCESS"
export const GET_FILE_BYID_FAILURE = "GET_FILE_BYID_FAILURE"

export const UPDATE_FILE_REQUEST = "UPDATE_FILE_REQUEST"
export const UPDATE_FILE_SUCCESS = "UPDATE_FILE_SUCCESS"
export const UPDATE_FILE_FAILURE = "UPDATE_FILE_FAILURE"

export const DELETE_FILE_REQUEST = "DELETE_FAIL_REQUEST"
export const DELETE_FILE_SUCCESS = "DELETE_FAIL_SUCCESS"
export const DELETE_FILE_FAILURE = "DELETE_FILE_FAILURE"